/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/drone_scout.glb 
Author: CloudHubOmniTeam (https://sketchfab.com/cloudhub)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drone-scout-e59c7360a74a4ca7ab84cb8069435bfd
Title: Drone Scout
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function AirPlane(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/drone_scout.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (props.isRotating) {
      actions["hover"].play();
    } else {
      actions["hover"].stop();
    }
  }, [actions, props.isRotating]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2.3, 0, 0]}
          scale={1}
          // position={[0, -2, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal1_1">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="drone44_44_correction">
                      <group name="drone44_44" />
                    </group>
                    <skinnedMesh
                      name="Object_50"
                      geometry={nodes.Object_50.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_50.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/drone_scout.glb");
